name: Profiling

on:
  push:
    branches: [ pillow-jpls ]
  pull_request:
    branches: [ pillow-jpls ]

  workflow_dispatch:

jobs:
  valgrind:
    name: Valgrind Memcheck
    runs-on: ubuntu-20.04
    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install prerequisites
        run: |
          sudo apt-get install valgrind

      - name: Build and install package for Valgrind
        run: |
          python setup.py --build-type=RelWithDebInfo install -- -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O0 -g"

