name: CI

on:
  push:
    branches: [ pillow-jpls ]
  pull_request:
    branches: [ pillow-jpls ]

  workflow_dispatch:

jobs:
  build:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pep517

      - name: build package
        run: |
          python -m pep517.build --binary .