name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2016, macos-10.15 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Static Analysis
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 --count --max-line-length=120 --statistics pillow_jpls

      - name: Build wheels with cibuildwheel
        uses: joerick/cibuildwheel@v1.9.0
        env:
           CIBW_SKIP: cp27-* cp35-*
           CIBW_TEST_REQUIRES: pytest numpy
           CIBW_TEST_COMMAND: pytest -v {project}/test
           MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Upload wheel files
        uses: actions/upload-artifact@v2
        with:
            path: ./wheelhouse/*.whl
