name: CI

on:
  push:
    branches: [ pillow-jpls ]
  pull_request:
    branches: [ pillow-jpls ]

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019 ]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.9.0
        env:
           CIBW_SKIP: cp27-* cp35-*
           CIBW_TEST_REQUIRES: pytest
           CIBW_TEST_COMMAND: pytest -v {project}/test

      - uses: actions/upload-artifact@v2
        with:
            path: ./wheelhouse/*.whl